language: c

matrix:
  include:
      # OSX
      - os: osx
        name: "MacOS Catalina"
        osx_image: xcode12

      # WSL
      - os: windows
        name: "WSL"
        env:
          - WSL_INSTALL=1
          - USE_CONDA=0

      # Windows
      - os: windows
        name: "Windows"
        env:
          - WSL_INSTALL=0

      # Linux
      - os: linux
        dist: bionic
        name: "Ubuntu Bionic"
        env:
          - USE_CONDA=1
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - xvfb

      - os: linux
        dist: focal
        name: "Ubuntu focal"
        env:
          - NEURON_VERSION=7.7
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - xvfb

before_install:
  - | # common environment exports for all subshells (scripts)
    export TRAVIS_TESTING=1
    export DISPLAY=:0
    export LOGFILE="hnn_travis.log"
  - | # Run prerequisite installation script
    if [ "${WSL_INSTALL}" ] && [ "${WSL_INSTALL}" -eq 1 ]; then
      echo "Installing WSL prerequisites"
      scripts/setup-travis-wsl.sh
    else
      echo "Installing ${TRAVIS_OS_NAME} prerequisites"
      scripts/setup-travis-${TRAVIS_OS_NAME}.sh

      source "$HOME/Miniconda3/etc/profile.d/conda.sh"
      conda activate hnn
    fi

install:
  - | # set up hnn module and testing packages
    if [[ "${WSL_INSTALL}" -ne 1 ]]; then
      pip install flake8 pytest pytest-cov coverage coveralls mne pytest-qt
      command cd $TRAVIS_BUILD_DIR
      python setup.py install
    else
      wsl -- pip install flake8 pytest pytest-cov coverage coveralls mne \
                 pytest-qt
      wsl -- python3 setup.py install
    fi

script:
  - | # run tests
    if [[ "${WSL_INSTALL}" -eq 1 ]]; then
      # helper commands from docker_functions.sh and utils.sh
      source "scripts/docker_functions.sh"
      set_globals
      source scripts/utils.sh
      export -f cleanup

      find_command_suggested_path "vcxsrv" "/c/Program Files/VcXsrv"
 
      # script_fail prints out the log before quitting so we can troubleshoot
      start_vcxsrv_print || script_fail
      wsl -- //home/hnn_user/hnn/scripts/run-travis-wsl.sh
      stop_vcxsrv || script_fail
    else
      echo "Running Python tests on host OS..."
      pwd
      command cd $TRAVIS_BUILD_DIR
      pwd
      py.test --cov=. hnn/tests/
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
