name: hnn
channels:
- defaults
dependencies:
- python=3.7
- pip
- numpy
- scipy
- matplotlib
- psutil
- pip:
  - NEURON
  - https://api.github.com/repos/jonescompneurolab/hnn-core/zipball/master
  - PyQt5